### ISSUE TITLE
Match logo background color with furo theme

### ISSUE THREAD

**Issue by fraya** [dylan-lang/website#144]
The logo background color does not match with furo theme neither in light or dark mode.

**Comment by cgay** [comment]
I think some of the images in the dylan-artwork repo have transparent backgrounds if you want to give them a try.

**Comment by cgay** [comment]
Should be fixed by #149 but the `website` submodule in `opendylan` needs to be updated to get the change.

**Comment by fraya** [comment]
Fixed
