### ISSUE TITLE
Dylan book PDF and ePub links broken

### ISSUE THREAD

**Issue by staypufd** [dylan-lang/website#147]
Dylan book PDF and ePub links broken

**Comment by cgay** [comment]
https://opendylan.org/books/dpg/DylanProgramming.pdf and .epub now exist.

I will leave this bug open because we need to make building them be part of the normal documentation build process.

Thanks for the report!

**Comment by cgay** [comment]
TBH I'm not planning to fix this specific issue anymore. But DPG is now a Dylan package and I may at some point think about generating epub and pdf versions of each package. If that happens it will fix DPG as well.
