### ISSUE TITLE
Footer on big monitors (or short pages)

### ISSUE THREAD

**Issue by fracek** [dylan-lang/website#51]
Cgay reported this a couple of weeks ago, on big monitors the footer was in the middle of the page. If you have a small monitor you can see what I mean on the [about page](http://opendylan.org/about/index.html).

Abeaumont (IIRC) linked to [this](http://twitter.github.com/bootstrap/examples/sticky-footer-navbar.html) page, where they use a sticky footer with boostrap and a fixed navbar.

To achieve that result we need to wrap the navbar and container in a wrap div and add a bit of css.

To do this we can:
1. define a new theme and layout by modifying the basic theme
2. change the current layout, open the wrap in the header block and close it in the footer block.

I implemented option 2 in a feature branch in my fork ([commit](https://github.com/fracek/website/commit/36344f42082e2546e7430ba50900df3219d3c4f9)) but I don't know if putting the open/close tags in two different blocks will cause any problem in the future.

**Comment by cgay** [comment]
Obsolete with #141
