### ISSUE TITLE
Short summary of features

### ISSUE THREAD

**Issue by fracek** [dylan-lang/website#52]
@cgay suggested this on IRC, [Rust](http://www.rust-lang.org/) website has a list of the language features. We could put something like that above the code carousel.

If you are okay with this please write the list of the features.

**Comment by cgay** [comment]
I think this will fit in with the "Tour of Dylan", which will be based on the "About" pages on the website that were never linked from anywhere (or got unlinked accidentally). It just needs to be expanded a bit.
