### ISSUE TITLE
Confusing intro of dylan-user

### ISSUE THREAD

**Issue by SeanTAllen** [dylan-lang/website#69]
http://opendylan.org/documentation/intro-dylan/modules-libraries.html

In Libraries section. 2nd paragraph and start of third both introduce dylan-user in fashion that is quite confusing.

**Comment by cgay** [comment]
Yes, it's terrible. :(

**Comment by cgay** [comment]
Actually, I'm going to re-report this against the opendylan repo since that's where the doc lives.

**Comment by cgay** [comment]
dylan-lang/opendylan/issues/1209
