### ISSUE TITLE
can not build 

### ISSUE THREAD

**Issue by xieyuheng** [dylan-lang/website#74]
~/lang/dylan/website master
make 
sphinx-build -b html -d build/doctrees  source build/html
Running Sphinx v1.3.1

Extension error:
Could not import extension dylandomain.dylandomain (exception: No module named 'dylandomain')
Makefile:29: recipe for target 'html' failed
make: *** [html] Error 1

**Comment by xieyuheng** [comment]
~/lang/dylan/website master
python --version                              
Python 3.4.3

**Comment by waywardmonkeys** [comment]
Did you do a ``git clone --recursive`` or a ``git submodule update --init``?

**Comment by waywardmonkeys** [comment]
(The real point is: Do you have a populated ``sphinx-extensions`` directory within the root directory of the repository?)

**Comment by xieyuheng** [comment]
129  ~/lang/dylan/website master
git submodule update --init
Submodule 'sphinx-extensions' (git://github.com/dylan-lang/sphinx-extensions.git) registered for path 'sphinx-extensions'
Cloning into 'sphinx-extensions'...
remote: Counting objects: 208, done.
remote: Total 208 (delta 0), reused 0 (delta 0), pack-reused 208
Receiving objects: 100% (208/208), 80.91 KiB | 114.00 KiB/s, done.
Resolving deltas: 100% (72/72), done.
Checking connectivity... done.
Submodule path 'sphinx-extensions': checked out '4b144b22d31fa4878aa5379603e0114847bcfecb'

  ~/lang/dylan/website master
l 
build/  make.bat  Makefile  README.rst  source/  sphinx-extensions/

  ~/lang/dylan/website master
make                                                      
sphinx-build -b html -d build/doctrees  source build/html
Running Sphinx v1.3.1

Extension error:
Could not import extension dylandomain.dylandomain (exception: No module named 'urlparse')
Makefile:29: recipe for target 'html' failed
make: *** [html] Error 1

2  ~/lang/dylan/website master

**Comment by waywardmonkeys** [comment]
You'll need to ``easy_install urlparse`` or similar.

**Comment by waywardmonkeys** [comment]
It is also worth noting that I don't know if anyone has tried this before with Python 3.

**Comment by xieyuheng** [comment]
I give up trying :P  

I am so unfamiliar with python 

I am closing this issue

**Comment by waywardmonkeys** [comment]
I'm working on fixing some of the issues ... I'll be landing changes over the coming day or two.
